SECRET_KEY = "SFAFOUHAFUAHSDLADHLASJDLASDJLKADJALSDJA"

HOSTNAME = "127.0.0.1"
PORT = 3306
USERNAME = "root"
PASSWORD = "000000"
DATABASE = "cd_vinyl"
DB_URI = "mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8".format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI

